In [1]:
import os 
import numpy as np 
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [3]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [4]:
from sklearn.preprocessing import LabelEncoder

In [10]:
path = "breast-cancer.csv"
if not os.path.exists(path):
    raise FileNotFoundError(f"{path} is not exist")
else:
    print('nothing happend, continue!')

nothing happend, continue!

In [5]:
df = pd.read_csv("breast-cancer.csv")

In [6]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [11]:
y_raw = df["diagnosis"]
X = df.drop(columns=["diagnosis"])

In [13]:
le = LabelEncoder()
y = le.fit_transform(y_raw) #M --> 1, B-->0
class_names = list(le.classes_)

In [14]:
class_names

['B', 'M']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [16]:
rf = RandomForestClassifier(n_estimators=300, max_depth=None, min_samples_split=2, n_jobs=-1)

In [17]:
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=300, n_jobs=-1)

In [18]:
y_pred = rf.predict(X_test)

In [19]:
acc = accuracy_score(y_test, y_pred)
acc

0.9736842105263158

In [21]:
print(classification_report(y_test, y_pred, target_names=class_names))

              precision    recall  f1-score   support

           B       0.96      1.00      0.98        72
           M       1.00      0.93      0.96        42

    accuracy                           0.97       114
   macro avg       0.98      0.96      0.97       114
weighted avg       0.97      0.97      0.97       114

In [22]:
sample = X_test.iloc[[0]]
sample

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
120,865137,11.41,10.82,73.34,403.3,0.09373,0.06685,0.03512,0.02623,0.1667,...,12.82,15.97,83.74,510.5,0.1548,0.239,0.2102,0.08958,0.3016,0.08523

In [26]:
true_label = y_test[0]
true_label

0

In [25]:
pred_label = rf.predict(sample)[0]
pred_label

0