In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import joblib

In [2]:
df = pd.read_csv('iris.csv')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [4]:
df['species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [5]:
X = df.drop(columns=["species"])
y = df["species"]

In [7]:
le = LabelEncoder()
y_enc = le.fit_transform(y)

#setosa -->> 0, versicolor --> 1, virginica --> 2

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y_enc, test_size=0.2, random_state=42, stratify=y_enc)

In [10]:
model = LogisticRegression(max_iter=200)

In [11]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [12]:
y_pred = model.predict(X_test)

In [13]:
y_pred

array([0, 2, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 1, 2, 0, 2,
       1, 2, 2, 2, 1, 0, 2, 0])

In [14]:
acc = accuracy_score(y_test, y_pred)
acc

0.9666666666666667

In [15]:
le.classes_

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [17]:
print(classification_report(y_test, y_pred, target_names=le.classes_))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.90      0.95        10
   virginica       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

In [23]:
joblib.dump(model, "lr_iris.pkl")
joblib.dump(le, "lr_iris_le.pkl")

['lr_iris_le.pkl']

In [19]:
new_sample=pd.DataFrame([[5.1, 3.5, 1.4, 0.2]], 
                       columns=["sepal_length", "sepal_width", "petal_length", "petal_width"])

In [20]:
new_sample

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2

In [24]:
import joblib
import pandas as pd
model = joblib.load("lr_iris.pkl")
le = joblib.load("lr_iris_le.pkl")

In [25]:
pred_lbl = model.predict(new_sample)
pred_lbl

array([0])

In [27]:
pred_cls = le.inverse_transform(pred_lbl)
pred_cls[0]

'setosa'